version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: spk_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spk_profile_matching
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
